sudo: false

language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.ivy2

addons:
  postgresql: '9.5'

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-sv

addons:
  chrome: stable

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
  - psql -c "create database signup;" -U postgres
  - psql signup -c "create user signup4 password 's7p2+';" -U postgres
  - psql signup -c "grant all privileges on database signup to signup4;" -U postgres

env: APPLICATION_BASE_URL=http://127.0.0.1:19001 LANG=sv_SE TZ=Europe/Stockholm

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - sbt -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver 'testOnly se.crisp.signup4.unit.* se.crisp.signup4.integration.* se.crisp.signup4.acceptance.*'

deploy:
  provider: heroku
  api_key:
    secure: EGY8+PYoTEN8HXSNZJmCosHvyK2FLOgZboEunJARqZw8Dn530CkCWKPKV3GkCbtCVzFYg6g5bw4r5Gzk2/e9k2HDRqsi6BS1gMjyuVed0Fbxo25xBEPl3kiHyIX9GaNgLUqlZMOpPwIC96+h6yBnI2AWsJ6goiWv2/i5gY7cTow=
  app: signup-ci-test
