sudo: false

language: scala
scala:
  - 2.11.4
jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.ivy2

addons:
  postgresql: '9.1'

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-sv

before_script:
  - psql -c "create database signup;" -U postgres
  - psql signup -c "create user signup4 password 's7p2+';" -U postgres
  - psql signup -c "grant all privileges on database signup to signup4;" -U postgres

env: WEB_DRIVER_TYPE=phantomjs APPLICATION_BASE_URL=http://127.0.0.1:3333 LANG=sv_SE TZ=Europe/Stockholm

script:
  - sbt 'test-only unit.* integration.* acceptance.*'

deploy:
  provider: heroku
  api_key:
    secure: EGY8+PYoTEN8HXSNZJmCosHvyK2FLOgZboEunJARqZw8Dn530CkCWKPKV3GkCbtCVzFYg6g5bw4r5Gzk2/e9k2HDRqsi6BS1gMjyuVed0Fbxo25xBEPl3kiHyIX9GaNgLUqlZMOpPwIC96+h6yBnI2AWsJ6goiWv2/i5gY7cTow=
  app: signup-ci-test
